# Be aware the health of this package is based on these
# analyse options, we will get the most health points if
# we do not change anything, see:
# https://pub.dev/help#health

include: package:flutter_lints/flutter.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - unnecessary_brace_in_string_interps
    - non_constant_identifier_names
    - cancel_subscriptions

analyzer:
  errors:
    invalid_dependency: ignore # Ignored for local platform_interface dependency
